### ISSUE TITLE
GM free scrolls issues

### ISSUE THREAD

**Issue by tirzah2** [p4535992/foundryvtt-terre-selvagge-dnd5e#1]
Buongiorno!
Il GM gli viene controllato se ha i material components, e glieli rimuove quando fa la scroll. (non i time coins, non i gp)

https://github.com/p4535992/foundryvtt-terre-selvagge-dnd5e/blob/86241476298c9e539c68cf35e56f6a529f7cec0e/src/scripts/lib/scroll-helpers.js#L425

**Comment by p4535992** [comment]
risolto con 0.0.46
